server:
  port: 8050 # 指定该Eureka实例的端口号
eureka:
  instance:
    prefer-ip-address: true  # 是否显示主机的IP
  client:
    service-url:
      defaultZone: http://159.75.44.25:8761/eureka/  # 指定Eureka服务端地址
spring:
  application:
    name: microservice-gateway-zuul # 指定应用名称
zuul: 
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    order-service:
      path: /order-service/**
      serviceId: order-service
